### ISSUE TITLE
Infinite recursion in get_web_session()

### ISSUE THREAD

**Issue by fourcube** [ValvePython/steam#144] opened 2018-02-20 08:19 UTC
This seems to be related to an issue with gevent and python 3.6. (https://github.com/gevent/gevent/issues/941)

I was able to fix it by following https://github.com/gevent/gevent/issues/941#issuecomment-281497659.

**Comment by rossengeorgiev** [comment] 2018-02-20 08:23
Duplicate of #97

**Closed by rossengeorgiev** 2018-02-20 08:23 UTC
