### ISSUE TITLE
Steam ratelimit raises confusing exception type

### ISSUE THREAD

**Issue by Hexiro** [ValvePython/steam#338] opened 2021-06-14 13:01 UTC
When ratelimited, Steam will give the response, "There have been too many login failures from your network in a short time period. Please wait and try again later." After reading your webauth code, on lines 228-230 it just uses an `else` keyword to raise `LoginIncorrect` if the exception doesn't match any other. Which can be confusing in my opinion, as your login credentials could be correct, but steam is just not accepting your requests at that time. Maybe another elif can be used to check for `clear_password_field` and then an else statement can raise `HTTPError` as a more generalized exception for when something unexpected goes wrong. Let me know what you think about this!

**Comment by rossengeorgiev** [comment] 2021-06-14 15:49
You are correct. Duplicate of #316

**Closed by rossengeorgiev** 2021-06-14 15:49 UTC
